### ISSUE TITLE
Is the library supposed to work on MacOS?

### ISSUE THREAD

**Issue by bparvanov** [HexaEngine/Hexa.NET.ImGui#24]
I tried to run ExampleMinimal and the following exception throws:

System.InvalidOperationException: Context not created.
   at Hexa.NET.KittyUI.Windows.SdlContext.AssertCreated() in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/Windows/SdlContext.cs:line 81
   at Hexa.NET.KittyUI.Windows.SdlContext.SwapInterval(Int32 interval) in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/Windows/SdlContext.cs:line 165
   at Hexa.NET.KittyUI.Windows.Window.Initialize(AppBuilder appBuilder) in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/Windows/Window.cs:line 75
   at Hexa.NET.KittyUI.Application.RegisterWindow(IRenderWindow window) in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/Application.cs:line 103
   at Hexa.NET.KittyUI.Windows.CoreWindow.Show() in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/Windows/CoreWindow.cs:line 191
   at Hexa.NET.KittyUI.Application.Run(IRenderWindow mainWindow, AppBuilder builder) in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/Application.cs:line 54
   at Hexa.NET.KittyUI.AppBuilder.Run() in /Users/borislav/Projects/Hexa.NET.KittyUI/Hexa.NET.KittyUI/AppBuilder.cs:line 30
   at Program.<Main>$(String[] args) in /Users/borislav/Projects/Hexa.NET.KittyUI/ExampleMinimal/Program.cs:line 9

I tested it on MacOS Sonoma 14.6.1, the CPU is M1 (ARM)

**Comment by JunaMeinhold** [comment]
@bparvanov are you still there?

**Comment by bparvanov** [comment]
Yes, sorry, I thought that you deleted the issue, but you actually moved it...

Yes, I replaced with the new .dylib files and the project ExampleGLFWOpenGL3 worked... 
Can you update the nuget packages, please..

Thanks again

**Comment by JunaMeinhold** [comment]
Should be soon available on nuget, after that I'll update the deps of the framework.

**Comment by JunaMeinhold** [comment]
And done now we just have to wait for nuget
![image](https://github.com/user-attachments/assets/3ddfc4df-162a-4601-a29b-33fc09fca38c)
